# Generated by Django 3.2.7 on 2021-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spare_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(verbose_name='3')),
                ('brand', models.TextField()),
                ('vehicle', models.TextField()),
                ('price', models.IntegerField(verbose_name='6')),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
