# Generated by Django 3.2.7 on 2021-09-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211001_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='vehicle',
            field=models.CharField(choices=[('corolla', 'corolla'), ('hilux', 'hilux')], default='hilux', max_length=100),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
