# Generated by Django 3.2.7 on 2021-10-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211001_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='image',
            field=models.ImageField(upload_to='static/spare'),
        ),
    ]
